#!/bin/bash -e

SLAVE_ID=$(cat /slaveid)
HOST_IP=$(ip route show | grep '^default' | awk '{print $3}')

while true; do
    redis-cli -h ${HOST_IP} --csv expire slave:${SLAVE_ID} 20 > /dev/null
    sleep 10
done

