---
# Slave settings
- file: path=/opt/jenkins/.ssh state=directory owner=jenkins group=jenkins mode=700
- authorized_key: user=jenkins key="{{item}}"
  with_file:
  - jenkins_id_rsa.pub
  - Jenkins_aws_system.pem.pub
- authorized_key: user=jenkins key='{{lookup("pipe", "cat /opt/build/hudson/authorized_keys/id_*.pub" )}}'
- copy: src=91-cloudimg-jenkins dest=/etc/sudoers.d/91-cloudimg-jenkins
        mode=440 owner=root group=root
- copy: src=~/.ssh/jenkins_id_rsa dest=/opt/jenkins/.ssh/id_rsa
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=jenkins_id_rsa.pub dest=/opt/jenkins/.ssh/id_rsa.pub
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=jenkins_ssh_config dest=/opt/jenkins/.ssh/config
        owner=jenkins group=jenkins mode=600 backup=no
- file: path=/opt/jenkins/.m2 state=directory owner=jenkins group=jenkins
- name: Add m2 repo seed (aws)
  synchronize: src=/opt/build/m2_repo_seed/ dest=/opt/jenkins/.m2/repo_seed
        owner=true group=true
  when: "'aws' in group_names"
- name: Add m2 repo seed (docker)
  synchronize: src=/opt/build/m2_repo_seed/ dest=/opt/jenkins/.m2/repository
        owner=true group=true
  when: "'aws' not in group_names"
- name: Fix .m2 rights
  command: chown -R jenkins:jenkins /opt/jenkins/.m2
  changed_when: false
- copy: src=/opt/build/hudson/.profile dest=/opt/jenkins/.profile
        owner=jenkins group=jenkins backup=no
- copy: src=/opt/build/hudson/.bashrc dest=/opt/jenkins/.bashrc
        owner=jenkins group=jenkins backup=no
  when: "'aws' in group_names"
- copy: src=/opt/build/hudson/.netrc dest=/opt/jenkins/.netrc
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=/opt/build/hudson/.s3cfg dest=/opt/jenkins/.s3cfg
        owner=jenkins group=jenkins mode=600 backup=no

- name: Git config
  # should be backup=yes but create=true option is missing on ini_file
  ini_file: dest=/opt/jenkins/.gitconfig state=present backup=no owner=jenkins group=jenkins mode=640
            section=user option=name value="Jenkins Nuxeo"
- ini_file: dest=/opt/jenkins/.gitconfig state=present backup=no owner=jenkins group=jenkins mode=640
            section=user option=email value="jenkins@nuxeo.com"

- copy: src=/opt/build/hudson/gradle.properties dest=/opt/build/hudson/gradle.properties
        owner=jenkins group=jenkins
- copy: src=/opt/build/hudson/instance.clid dest=/opt/build/hudson/instance.clid
        owner=jenkins group=jenkins
- copy: src=use_mnt_ondemand.sh dest=/opt/jenkins/use_mnt.sh
        mode=755 owner=jenkins group=jenkins
  when: "'aws_ondemand' in group_names"

- synchronize: src=/opt/build/keystores dest=/opt/build/ owner=no group=no delete=yes recursive=yes rsync_path="sudo -u jenkins rsync"
  become_user: jenkins
  register: keystore_sync
- shell: chown -R jenkins:jenkins /opt/build/keystores
  when: keystore_sync.changed
- name: Kerberos krb5.conf
  copy: src=/opt/build/keystores/keytabs/krb5.conf dest=/etc/krb5.conf

- name: Setup Azure CLI
  shell: azure account import /opt/build/keystores/azure.nuxeo.com.publishsettings
  become_user: jenkins
  when: azure_install.changed

- name: Add jenkins to docker group
  user: name=jenkins groups=docker append=yes

- name: Start PostgreSQL
  shell: sv up postgresql
  changed_when: false
- name: Add nxadmin user
  script: create_pg_user.sh
  changed_when: false
- name: Stop PostgreSQL
  shell: sv down postgresql
  changed_when: false

