---
- name: Get Gradle package
  s3: bucket={{s3_bucket}} region={{s3_region}}
      object=/{{s3_tools_path}}/gradle-1.6-bin.zip dest=/tmp/gradle-1.6-bin.zip mode=get
      aws_access_key={{aws_id.msg}} aws_secret_key={{aws_secret.msg}}
- name: Install Gradle
  unarchive: src=/tmp/gradle-1.6-bin.zip dest=/opt/build/tools copy=no
- file: path=/tmp/gradle-1.6-bin.zip state=absent

- name: Add gradle symlink
  file: src=/opt/build/tools/gradle-1.6 path=/opt/build/tools/gradle state=link
- name: Set gradle alternative
  alternatives: name=gradle link=/usr/bin/gradle path=/opt/build/tools/gradle/bin/gradle

