---
- name: Preset MySQL password
  debconf: name=mysql-server question='mysql-server/root_password' value='nuxeo' vtype=password
- name: Preset MySQL password again
  debconf: name=mysql-server question='mysql-server/root_password_again' value='nuxeo' vtype=password
- name: Install MySQL
  apt: name={{item}} state=present
  with_items:
  - mysql-server
  - mysql-client
- name: Create MySQL runit dir
  file: path=/etc/service/mysql state=directory
- name: Add MySQL startup script
  copy: src=mysql dest=/etc/service/mysql/run mode=0755

