---
# file: roles/slave/tasks/nodejs.yml

- setup: filter=ansible_env

- name: Check for Node4
  stat: path=/opt/build/tools/node-v4.5.0-linux-x64
  register: node4_installed
- name: Get Node4 package
  s3: bucket={{s3_bucket}} region={{s3_region}}
      object=/{{s3_tools_path}}/node-v4.5.0-linux-x64.tar.xz dest=/tmp/node-v4.5.0-linux-x64.tar.xz mode=get
      aws_access_key={{aws_id.msg}} aws_secret_key={{aws_secret.msg}}
  when: not node4_installed.stat.exists
- name: Install Node4
  unarchive: src=/tmp/node-v4.5.0-linux-x64.tar.xz dest=/opt/build/tools copy=no
  when: not node4_installed.stat.exists
- name: Install npm 2.15.1
  npm: name=npm version=2.15.1 global=yes
  tags: nodejs
  environment:
    PATH: /opt/build/tools/node-v4.5.0-linux-x64/bin:{{ansible_env.PATH}}
- name: Install Node4 dependencies
  npm: name={{item.name}} version={{item.version}} global=yes
  with_items:
  - name: yo
    version: 1.4.6
  - name: grunt-cli
    version: 0.1.13
  - name: gulp
    version: 3.8.11
  - name: bower
    version: 1.3.12
  - name: unicode
    version: 0.6.1
  environment:
    PATH: /opt/build/tools/node-v4.5.0-linux-x64/bin:{{ansible_env.PATH}}
  tags: nodejs

- name: Check for Node6
  stat: path=/opt/build/tools/node-v6.4.0-linux-x64
  register: node6_installed
- name: Get Node6 package
  s3: bucket={{s3_bucket}} region={{s3_region}}
      object=/{{s3_tools_path}}/node-v6.4.0-linux-x64.tar.xz dest=/tmp/node-v6.4.0-linux-x64.tar.xz mode=get
      aws_access_key={{aws_id.msg}} aws_secret_key={{aws_secret.msg}}
  when: not node6_installed.stat.exists
- name: Install Node6
  unarchive: src=/tmp/node-v6.4.0-linux-x64.tar.xz dest=/opt/build/tools copy=no
  when: not node6_installed.stat.exists
- name: Install npm 3.10.7
  npm: name=npm version=3.10.7 global=yes
  environment:
    PATH: /opt/build/tools/node-v6.4.0-linux-x64/bin:{{ansible_env.PATH}}
- name: Install Node6 dependencies
  npm: name={{item.name}} version={{item.version}} global=yes
  with_items:
  - name: yo
    version: 1.4.6
  - name: grunt-cli
    version: 0.1.13
  - name: gulp
    version: 3.8.11
  - name: bower
    version: 1.3.12
  - name: unicode
    version: 0.6.1
  environment:
    PATH: /opt/build/tools/node-v6.4.0-linux-x64/bin:{{ansible_env.PATH}}
  tags: nodejs

- file: path=/tmp/node-v4.5.0-linux-x64.tar.xz state=absent
- file: path=/tmp/node-v6.4.0-linux-x64.tar.xz state=absent

- name: Remove old global node
  file: path=/usr/local/bin/node state=absent
- name: Remove old global npm
  file: path=/usr/local/bin/npm state=absent

- alternatives: name=node link=/usr/bin/node path=/opt/build/tools/node-v4.5.0-linux-x64/bin/node
- alternatives: name=npm link=/usr/bin/npm path=/opt/build/tools/node-v4.5.0-linux-x64/bin/npm
- alternatives: name=yo link=/usr/bin/yo path=/opt/build/tools/node-v4.5.0-linux-x64/bin/yo
- alternatives: name=grunt link=/usr/bin/grunt path=/opt/build/tools/node-v4.5.0-linux-x64/bin/grunt
- alternatives: name=gulp link=/usr/bin/gulp path=/opt/build/tools/node-v4.5.0-linux-x64/bin/gulp
- alternatives: name=bower link=/usr/bin/bower path=/opt/build/tools/node-v4.5.0-linux-x64/bin/bower
