---
- name: Java 6
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/jdk-6u45-linux-x64.bin mode=geturl
  changed_when: false
  failed_when: false
  register: java6
- command: "wget -q -Ocache/jdk-6u45-linux-x64.bin --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin'"
  args:
    creates: cache/jdk-6u45-linux-x64.bin
  when: java6.url is not defined

- name: Java 8
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/jdk-8u77-linux-x64.tar.gz mode=geturl
  changed_when: false
  failed_when: false
  register: java8
- command: "wget -q -Ocache/jdk-8u77-linux-x64.tar.gz --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.tar.gz'"
  args:
    creates: cache/jdk-8u77-linux-x64.tar.gz
  when: java8.url is not defined

