---
- name: NodeJS 4
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v4.5.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs4
- get_url: url=https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-x64.tar.xz
           dest=cache/node-v4.5.0-linux-x64.tar.xz
  when: nodejs4.url is not defined

- name: NodeJS 6
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v6.4.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs6
- get_url: url=https://nodejs.org/dist/v6.4.0/node-v6.4.0-linux-x64.tar.xz
           dest=cache/node-v6.4.0-linux-x64.tar.xz
  when: nodejs6.url is not defined
