#! /bin/sh
### BEGIN INIT INFO
# Provides:          Xvfb
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Start or stop Xvfb on display :1
# Description:       Starts or stops Xvfb:1 for headless stuff (Jenkins)
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=/usr/bin/Xvfb
DAEMON2=/usr/bin/x11vnc
DAEMON3=/usr/bin/fluxbox
[ -x "$DAEMON" ] || exit 0
[ -x "$DAEMON2" ] || exit 0
[ -x "$DAEMON3" ] || exit 0
NAME=Xvfb
NAME2=x11vnc
NAME3=fluxbox
DESC="X virtual framebuffer"
DESC2="Xvnc server"
DESC3="Fluxbox window manager"
USER="jenkins"
XVFB_OPTS=":1 -ac -screen 0 1280x1024x16"
XVNC_OPTS="-display :1 -nopw -forever -quiet"
FLUX_OPTS="-display :1"

. /lib/init/vars.sh

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --name $NAME --background \
		--chuid $USER --startas $DAEMON -- $XVFB_OPTS
	ES=$?
	log_end_msg $ES
	log_daemon_msg "Starting $DESC2" "$NAME2"
	start-stop-daemon --start --name $NAME2 --background \
		--chuid $USER --startas $DAEMON2 -- $XVNC_OPTS
	ES=$?
	log_end_msg $ES
	log_daemon_msg "Starting $DESC3" "$NAME3"
	start-stop-daemon --start --name $NAME3 --background \
		--chuid $USER --startas $DAEMON3 -- $FLUX_OPTS
	ES=$?
	log_end_msg $ES
	;;
  stop)
	log_daemon_msg "Stopping $DESC3" "$NAME3"
	start-stop-daemon --chuid $USER --stop --name $NAME3
	ES=$?
	log_daemon_msg "Stopping $DESC2" "$NAME2"
	start-stop-daemon --chuid $USER --stop --name $NAME2
	ES=$?
	log_end_msg $ES
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --chuid $USER --stop --name $NAME
	ES=$?
	log_end_msg $ES
	;;
  restart|force-reload)
 	/etc/init.d/xvfb stop
 	/etc/init.d/xvfb start
	;;
  *)
	echo "Usage: xvfb {start|stop|restart}" >&2
	exit 3
	;;
esac

:
