---
- name: Get the Google Linux package signing key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
- stat: path=/etc/apt/sources.list.d/google-chrome.list
  register: google_apt_rc
- name: Add Google Chrome stable repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list
  when: google_apt_rc.stat.exists == false
- name: Update apt cache
  apt: update_cache=yes
- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=installed
- name: Install ChromeDriver 2.16
  uri: creates=/tmp/chromedriver_linux64.zip
       url=http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip
       dest=/tmp/chromedriver_linux64.zip
- command: creates=/usr/bin/chromedriver chdir=/usr/bin
           unzip /tmp/chromedriver_linux64.zip
- file: path=/usr/bin/chromedriver mode=0755
