---
- name: Download JDK 8
  command: "wget -q -O/tmp/jdk-8-linux-x64.tgz --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/8u40-b26/jdk-8u40-linux-x64.tar.gz'"
  args:
    creates: /usr/lib/jvm/jdk1.8.0_40
- name: Install JDK 8
  command: tar xzf /tmp/jdk-8-linux-x64.tgz
  args:
    creates: /usr/lib/jvm/jdk1.8.0_40
    chdir: /usr/lib/jvm
  register: extracted_java8
- name: Remove JDK 8 archive
  file: path=/tmp/jdk-8-linux-x64.tgz state=absent
- name: Create JDK 8 symlink
  file: src=/usr/lib/jvm/jdk1.8.0_40 path=/usr/lib/jvm/java-8 state=link force=yes
  when: extracted_java8.changed

