---
- name: Configure user 'ubuntu'
  authorized_key: user=ubuntu key="{{item}}"
  with_file:
  - Jenkins_aws_system.pem.pub
- authorized_key: user=ubuntu key='{{lookup("pipe", "cat /opt/build/hudson/authorized_keys/id_*.pub" )}}'

- name: Configure user 'jenkins'
  file: path=/opt/jenkins state=directory
- user: name=jenkins home=/opt/jenkins state=present shell=/bin/bash
- file: path=/opt/jenkins/ state=directory owner=jenkins group=jenkins
- file: path=/opt/jenkins/.ssh state=directory owner=jenkins group=jenkins mode=700
- authorized_key: user=jenkins key="{{item}}"
  with_file:
  - jenkins_id_rsa.pub
  - Jenkins_aws_system.pem.pub
- authorized_key: user=jenkins key='{{lookup("pipe", "cat /opt/build/hudson/authorized_keys/id_*.pub" )}}'
- copy: src=91-cloudimg-jenkins dest=/etc/sudoers.d/91-cloudimg-jenkins
        mode=440 owner=root group=root
- copy: src=~/.ssh/jenkins_id_rsa dest=/opt/jenkins/.ssh/id_rsa
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=jenkins_id_rsa.pub dest=/opt/jenkins/.ssh/id_rsa.pub
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=jenkins_ssh_config dest=/opt/jenkins/.ssh/config
        owner=jenkins group=jenkins mode=600 backup=no
- file: path=/opt/jenkins/.m2 state=directory owner=jenkins group=jenkins
- copy: src=/opt/build/hudson/m2remote/settings.xml dest=/opt/jenkins/.m2/settings.xml
        owner=jenkins group=jenkins
- copy: src=/opt/build/m2_repo_seed/ dest=/opt/jenkins/.m2/repo_seed
        owner=jenkins group=jenkins
  when: "'aws' in group_names"
- copy: src=/opt/build/m2_repo_seed/ dest=/opt/jenkins/.m2/repository
        owner=jenkins group=jenkins
  when: "'aws' not in group_names"
- copy: src=/opt/build/hudson/.profile dest=/opt/jenkins/.profile
        owner=jenkins group=jenkins backup=no
- copy: src=/opt/build/hudson/.bashrc dest=/opt/jenkins/.bashrc
        owner=jenkins group=jenkins backup=no
  when: "'aws' in group_names"
- copy: src=/opt/build/hudson/.netrc dest=/opt/jenkins/.netrc
        owner=jenkins group=jenkins mode=600 backup=no
- copy: src=/opt/build/hudson/.s3cfg dest=/opt/jenkins/.s3cfg
        owner=jenkins group=jenkins mode=600 backup=no

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200
- name: Upgrade/install ansible dependencies
  apt: state=latest name={{item}}
  with_items:
  - aptitude
  - python-httplib2
  - apt-transport-https
- name: Update existing packages
  apt: upgrade=full
- name: Upgrade/install build dependencies
  apt: state=latest name={{item}}
  with_items:
  - python-httplib2
  - openjdk-6-jdk
  - openjdk-7-jdk
  - git
  - mercurial
  - subversion
  - chromium-browser
  - ant
  - ant-contrib
  - imagemagick
  # conflicts with custom build with x264 support
  # - ffmpeg
  - ffmpeg2theora
  - lynx
  - sysstat
  - logtail
  - gawk
  - vim
  - wget
  - curl
  - unzip
  - moreutils
  - ufraw
  - poppler-utils
  - libreoffice
  - libwpd-tools
  - xvfb
  - x11vnc
  - fluxbox
  - linkchecker
  - tree
  - libimage-exiftool-perl
  # Amazon S3
  - s3cmd
  # Funkload requirements
  - python-dev
  - python-setuptools
  - python-webunit
  - python-docutils
  - gnuplot
  - python-reportlab
  - python-pypdf
  - pgfouine
  # Drive requirements
  - python-pip
  - python-qt4
  - libffi-dev
  - python-virtualenv
- apt: state=latest name=tcpwatch-httpproxy install_recommends=no
- pip: name=logchart
- shell: easy_install -f http://funkload.nuxeo.org/snapshots/ -U funkload
- alternatives: name=editor path=/usr/bin/vim.basic
- file: src=/usr/lib/jvm/java-1.6.0-openjdk-amd64 path=/usr/lib/jvm/java-6-openjdk state=link
- file: src=/usr/lib/jvm/java-1.7.0-openjdk-amd64 path=/usr/lib/jvm/java-7-openjdk state=link
# Xvfb, x11vnc, fluxbox
- copy: src=xvfb dest=/etc/init.d/xvfb
        mode=755 owner=root group=root
- service: name=xvfb enabled=yes state=started
# FFmpeg build with x264, vpx and AAC support if needed
- copy: src=ffmpeg-compile.sh dest=/tmp/ffmpeg-compile.sh
        mode=755 owner=root group=root
- shell: /tmp/ffmpeg-compile.sh
  register: compile_ffmpeg
  changed_when: compile_ffmpeg.rc != 0
- file: path=/tmp/ffmpeg-nuxeo state=absent

- name: Tooling
  file: path=/opt/build state=directory owner=jenkins group=jenkins

- file: path=/opt/build/hudson state=directory owner=jenkins group=jenkins
- copy: src=/opt/build/hudson/gradle.properties dest=/opt/build/hudson/gradle.properties
        owner=jenkins group=jenkins
- copy: src=/opt/build/hudson/instance.clid dest=/opt/build/hudson/instance.clid
        owner=jenkins group=jenkins
- file: path=/opt/build/tools state=directory owner=jenkins group=jenkins
- copy: src=use_mnt_ondemand.sh dest=/opt/jenkins/use_mnt.sh
        mode=755 owner=jenkins group=jenkins
  when: "'aws_ondemand' in group_names"
- copy: src=use_mnt_static.sh dest=/opt/jenkins/use_mnt.sh
        mode=755 owner=jenkins group=jenkins
  when: "'aws_static' in group_names"

# Firefox
# Can't use APT which pulls unfixed FF version
- name: Check if Firefox 26 is installed
  shell: "firefox --version"
  register: ff26_installed
  ignore_errors: True
  changed_when: false
- include: firefox.yml
  when: (ff26_installed.rc != 0 or ff26_installed.stdout != 'Mozilla Firefox 26.0.0')

# Google Chrome
- include: google-chrome.yml
  tags: chrome

- name: Git config
  # should be backup=yes but create=true option is missing on ini_file
  ini_file: dest=/opt/jenkins/.gitconfig state=present backup=no owner=jenkins group=jenkins mode=640
            section=user option=name value="Jenkins Nuxeo"
- ini_file: dest=/opt/jenkins/.gitconfig state=present backup=no owner=jenkins group=jenkins mode=640
            section=user option=email value="jenkins@nuxeo.com"

# Maven
- include: maven.yml
  tags: maven

- name: Gradle 1.x
  uri: creates=/opt/build/tools/gradle
       url=http://services.gradle.org/distributions/gradle-1.6-bin.zip
       dest=/tmp/gradle-1.6-bin.zip
- command: creates=/opt/build/tools/gradle
           unzip /tmp/gradle-1.6-bin.zip -d /opt/build/tools/
- file: src=/opt/build/tools/gradle-1.6 path=/opt/build/tools/gradle state=link
- alternatives: name=gradle link=/usr/bin/gradle path=/opt/build/tools/gradle/bin/gradle
- file: path=/tmp/gradle-1.6-bin.zip state=absent

- name: Spot instance Jenkins callback script
# use https://qa.nuxeo.org/jenkins/plugin/ec2/AMI-Scripts/ubuntu-ami-setup.sh once ec2 plugin upgraded
  get_url: url=https://github.com/jenkinsci/ec2-plugin/raw/master/src/main/webapp/AMI-Scripts/ubuntu-init.py
           dest=/usr/bin/userdata mode=0750
- lineinfile: dest=/etc/rc.local backup=true state=present
              regexp='^python /usr/bin/userdata$' line='python /usr/bin/userdata' insertbefore='^exit 0'
- lineinfile: dest=/etc/rc.local backup=true state=present
              regexp='^.*use_mnt.sh.*$' line='/opt/jenkins/use_mnt.sh || true' insertbefore='^python /usr/bin/userdata'
  when: "'aws' in group_names"
- shell: ~jenkins/use_mnt.sh
  when: "'aws_static' in group_names"
- lineinfile: dest=/etc/hosts create=true state=present
              regexp='176.57.246.10' line='176.57.246.10 thorin thorin.in.nuxeo.com qa qa.nuxeo.org qapriv qapriv.nuxeo.org'
  when: "'docker' not in group_names"
- lineinfile: dest=/etc/hosts create=true state=present
              regexp='176.57.246.12' line='176.57.246.12 maven.in.nuxeo.com'
  when: "'docker' not in group_names"
- synchronize: src=/opt/build/keystores dest=/opt/build/ owner=no group=no delete=yes recursive=yes rsync_path="sudo -u jenkins rsync"
  sudo_user: jenkins

# Kerberos
- name: Kerberos krb5.conf
  copy: src=/opt/build/keystores/keytabs/krb5.conf dest=/etc/krb5.conf

# NodeJS
- name: Check for nodejs
  stat: path=/usr/local/bin/node
  register: node_path
  tags: nodejs
- include: nodejs.yml
  when: node_path.stat.exists == false
  tags: nodejs
- name: Install npm 2.7.0
  npm: name=npm version=2.7.0 global=yes
  tags: nodejs
- name: Install node dependencies
  npm: name={{item.name}} version={{item.version}} global=yes state=latest
  with_items:
  - name: yo
    version: 1.4.6
  - name: grunt-cli
    version: 0.1.13
  - name: gulp
    version: 3.8.11
  - name: bower
    version: 1.3.12
  tags: nodejs

# Azure CLI
- name: Install Azure CLI
  npm: name=azure-cli version=0.9.10 global=yes state=latest
  register: azure_install
- name: Setup Azure CLI
  shell: azure account import /opt/build/keystores/azure.nuxeo.com.publishsettings
  sudo_user: jenkins
  when: azure_install.changed

# Java versions
- include: java6.yml
  tags: java,java6
- include: java8.yml
  tags: java,java8

# Dart
- include: dart.yml
  tags: dart

# slave.jar
- name: Install current slave.jar
  file: path=/opt/jenkins/bin state=directory owner=jenkins group=jenkins
- get_url: url=http://qa.nuxeo.org/jenkins/jnlpJars/slave.jar
           dest=/opt/jenkins/bin/slave.jar
  sudo_user: jenkins
- name: Install startup wrapper
  copy: src=start_slave.sh dest=/opt/jenkins/start_slave.sh
        mode=0755 owner=jenkins group=jenkins
  when: "'docker' in group_names and 'multidb' in group_names"

- name: Upgrade/install Redis packages
  apt: state=latest name={{item}}
  with_items:
  - redis-server
  - redis-tools
  tags: redis
