---
- name: Delete database
  postgresql_db: name={{dbname}} encoding='UTF-8' state=absent
  sudo_user: postgres
  when: reset_data is defined and reset_data
- name: Create database
  postgresql_db: name={{dbname}} encoding='UTF-8' state=present template="template1"
  sudo_user: postgres
- name: Create user
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpass}} priv=ALL role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo_user: postgres

