---
- name: PostgreSQL packages
  apt: name={{item}} state=present
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  register: pginstall
  when: stage is not defined or stage == 'init'

- name: Start PostgreSQL
  service: name="postgresql" state="started"

- name: Initialize PostgreSQL
  include: pginit.yml
  when: pginstall.changed and (stage is not defined or stage == 'init')
- name: Setup PostgreSQL
  include: pgsetup.yml
  when: pginstall.changed and (stage is not defined or stage == 'init')

- name: Setup database
  include: dbsetup.yml
  when: stage is not defined or stage == 'setup'
