---
- include: docker_start.yml
  vars:
    dgroups:
    - docker
    - nuxeo
    count: 1
    expose:
    - 8080
    ports:
    - 0.0.0.0:8080:8080

- hosts: nuxeo
  gather_facts: yes
  sudo: yes
  roles:

  # Command setup
  - {role: common}

  # Install packages and download distribution
  - {role: postgresql-server, stage: init}
  - {role: nuxeo, stage: init}

  # Prepare for updates
  - {role: nuxeo, stage: stop}
  - {role: postgresql-server, stage: stop}

  # Update configuration/data
  - {role: postgresql-server, stage: setup}
  #- {role: postgresql-server, stage: setup, when: pginstall.changed or distribution_changed|bool}
  - {role: nuxeo, stage: setup}
  #- {role: postgresql-server, stage: setup, when: distribution_changed|bool}

  # Complete update
  - {role: postgresql-server, stage: start}
  - {role: nuxeo, stage: start}

#- include: docker_stop.yml
#  vars:
#    dgroups:
#    - nuxeo
#    count: 1

