---
- hosts: localhost
  gather_facts: no
  sudo: no
  connection: local
  tasks:
  - name: Remove test container
    docker: image="nuxeo/ansibletest" name="{{item}}" state=absent
    with_sequence: start=0 end={{count|int|default(1) - 1}} format="{{dgroups|join('_')|default('ansibletest')}}_%d"

