---
- name: Find PostgreSQL config file
  shell: psql -t -P format=unaligned -c 'show config_file'
  sudo_user: postgres
  register: pgconf
  changed_when: false
- name: Find PostgreSQL hba file
  shell: psql -t -P format=unaligned -c 'show hba_file'
  sudo_user: postgres
  register: pghba
  changed_when: false
- name: PostgreSQL listen address
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?listen_addresses\s*='
    line="listen_addresses = '*'"
    state=present
  when: dbhost != '127.0.0.1' and dbhost != 'localhost'
  notify: Restart PostgreSQL
- name: PostgreSQL max_connections
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?max_connections\s*='
    line="max_connections = {{max_connections}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL max prepared transactions
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?max_prepared_transactions\s*='
    line="max_prepared_transactions = {{max_prepared_transactions}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL shared buffers
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?shared_buffers\s*='
    line="shared_buffers = {{shared_buffers}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL effective cache size
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?effective_cache_size\s*='
    line="effective_cache_size = {{effective_cache_size}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL work mem
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?work_mem\s*='
    line="work_mem = {{work_mem}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL maintenance work mem
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?maintenance_work_mem\s*='
    line="maintenance_work_mem = {{maintenance_work_mem}}"
    state=present
  notify: Restart PostgreSQL
- name: PostgreSQL WAL buffers
  lineinfile: dest={{pgconf.stdout}}
    regexp='^#?wal_buffers\s*='
    line="wal_buffers = {{wal_buffers}}"
    state=present
  notify: Restart PostgreSQL
- name: Enable remote db access
  lineinfile: dest={{pghba.stdout}}
    regexp='^host\s*all\s*all\s*0\.0\.0\.0/0\s*md5'
    line="host all all 0.0.0.0/0 md5"
    state=present
  when: dbhost != '127.0.0.1' and dbhost != 'localhost'
  notify: Restart PostgreSQL
- name: Execute handlers
  meta: flush_handlers

